import { hashPassword } from "better-auth/crypto";

import {
  databaseNameFor,
  executeFile,
  executeFileArgs,
  parseRemoteArgs,
  queryRemoteRows,
  usageFor,
  writeSqlFile,
  type RemoteTarget,
} from "./remote-d1";

/**
 * Creates the one owner account on a remote D1 database.
 *
 * ## Why this is separate from the content seed
 *
 * The content seed may be run repeatedly and is inert if it meets rows it did
 * not write. A password cannot be: it is a credential, it is hashed on purpose,
 * and re-running it would either fail (good) or silently mint a second way into
 * the account (not good). So credentials get their own script, their own file,
 * and their own refusal.
 *
 * ## The refusal
 *
 * Before anything is generated at apply time, the script asks the target
 * database whether *any* user row exists, and stops if one does — with the
 * addresses it found, so the operator can see which account is already there.
 * The application ships with sign-up disabled and a single owner role, so one
 * row is the whole expected state and a second row is never a thing to create
 * quietly.
 *
 * The generated SQL carries no `ON CONFLICT` clause either. If a row appears
 * between the check and the apply, the insert violates the unique email index,
 * wrangler's file import fails, and the database is left as it was — wrangler
 * reports a failed import as a rollback. The check gives the friendly message;
 * the database gives the guarantee.
 *
 * ## The password
 *
 * Read from the environment (`OWNER_PASSWORD`, normally in `.dev.vars`), never
 * from an argument and never from the repository. What lands in the SQL file is
 * the `hashPassword` output — the same hashing Better Auth verifies at sign-in —
 * so the plaintext exists only in the process that generated the file. The file
 * itself is written under the gitignored `.wrangler/`.
 *
 * ## Usage
 *
 * ```bash
 * npm run db:provision:owner -- --env preview     # print the SQL, execute nothing
 * npm run db:provision:owner -- --env preview --apply
 * npm run db:provision:owner -- --env production --apply
 * ```
 */

/**
 * Mirrors `minPasswordLength` in `src/auth.ts`.
 *
 * A shorter password would be hashed happily here and then refused by Better
 * Auth at sign-in, so the check moves to where the mistake is cheapest to fix.
 * `tests/unit/remote-init.test.ts` asserts the two numbers stay equal.
 */
export const MIN_PASSWORD_LENGTH = 12;

export interface OwnerProvisioning {
  email: string;
  name: string;
  password: string;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** The pre-flight question: is there already an account on this database? */
export function existingOwnerCommand(): string {
  return "SELECT email FROM user ORDER BY created_at";
}

/** Wraps a refusal so a script run exits non-zero with a readable reason. */
export class OwnerAlreadyExistsError extends Error {
  constructor(target: RemoteTarget, emails: string[]) {
    super(
      [
        `Refusing to provision the ${target} database: it already has ${emails.length} account(s):`,
        ...emails.map((email) => `  - ${email}`),
        "",
        "Nothing was written. If this is the owner's account, the database is already",
        "provisioned; sign in instead. Creating a second account is not a supported",
        "state, so this script will not do it.",
      ].join("\n"),
    );
    this.name = "OwnerAlreadyExistsError";
  }
}

/**
 * The three statements that create the account, hashed password included.
 *
 * Deliberately without `ON CONFLICT`: every one of them must succeed or none of
 * them may run, and wrangler's import executes the file as a single unit.
 */
export async function buildOwnerSql(
  owner: OwnerProvisioning,
  userId: string = crypto.randomUUID(),
): Promise<string> {
  return [
    `-- Generated by scripts/provision-owner.ts. Do not edit by hand.`,
    `-- Contains the password *hash*, not the password. Gitignores itself by living`,
    `-- under .wrangler/. The account is created only if no user row exists yet; the`,
    `-- script checked before it wrote this file.`,
    `-- Apply with: wrangler d1 execute <database> --remote --file <this file>`,
    "",
    `INSERT INTO user (id, name, email, email_verified, image, created_at, updated_at)`,
    `  VALUES (${sqlString(userId)}, ${sqlString(owner.name)}, ${sqlString(owner.email)}, 1, NULL, unixepoch(), unixepoch());`,
    "",
    `INSERT INTO account (id, user_id, account_id, provider_id, password, created_at, updated_at)`,
    `  VALUES (${sqlString(crypto.randomUUID())}, ${sqlString(userId)}, ${sqlString(userId)}, 'credential', ${sqlString(await hashPassword(owner.password))}, unixepoch(), unixepoch());`,
    "",
    `INSERT INTO profiles (id, role, display_name, created_at, updated_at)`,
    `  VALUES (${sqlString(userId)}, 'owner', ${sqlString(owner.name)}, unixepoch(), unixepoch());`,
    "",
  ].join("\n");
}

/** The name of the generated file, kept next to the wrangler state it serves. */
export const OWNER_SQL_FILE = "owner-provision.sql";

export function assertPasswordUsable(password: string): void {
  if (password.length < MIN_PASSWORD_LENGTH) {
    throw new Error(
      `OWNER_PASSWORD is ${password.length} characters; Better Auth refuses anything shorter than ${MIN_PASSWORD_LENGTH}. Choose a longer password before provisioning.`,
    );
  }
}

export async function runProvisionOwner(argv: string[]): Promise<void> {
  const args = parseRemoteArgs(argv);

  if (args.help) {
    console.log(
      usageFor("npm run db:provision:owner --", [
        "Requires OWNER_EMAIL and OWNER_PASSWORD in the environment or .dev.vars.",
        "Nothing is executed without --apply.",
      ]),
    );
    return;
  }

  if (args.target === null) {
    console.error(
      usageFor("npm run db:provision:owner --", ["--env is required; there is no default."]),
    );
    process.exitCode = 1;
    return;
  }

  const target: RemoteTarget = args.target;
  const databaseName = databaseNameFor(target);

  const { readEnvFile, requireEnv } = await import("./env");
  readEnvFile();
  const email = requireEnv("OWNER_EMAIL");
  const password = requireEnv("OWNER_PASSWORD");
  const name = process.env.OWNER_NAME ?? "Propriétaire";
  assertPasswordUsable(password);

  if (args.apply) {
    const rows = queryRemoteRows({
      target,
      databaseName,
      command: existingOwnerCommand(),
    });
    if (rows.length > 0) {
      throw new OwnerAlreadyExistsError(
        target,
        rows.map((row) => String(row.email ?? "(unknown)")),
      );
    }
  } else {
    console.log(
      `Dry run: the ${target} database will be checked for an existing account when --apply is used.`,
    );
  }

  const sql = await buildOwnerSql({ email, name, password });
  const filePath = writeSqlFile(OWNER_SQL_FILE, sql);

  if (!args.apply) {
    console.log(sql);
    console.log(`Written to ${filePath}. Nothing was executed.`);
    console.log("To apply it to the " + target + " database:");
    console.log(
      `  node node_modules/wrangler/bin/wrangler.js ${executeFileArgs({ target, databaseName, filePath }).join(" ")}`,
    );
    return;
  }

  console.log(`Applying ${filePath} to the ${target} database (${databaseName})...`);
  executeFile({ target, databaseName, filePath });
  console.log(`Owner account ${email} created. It is the only account on this database.`);
}

const invokedDirectly =
  process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/provision-owner.ts") === true;

if (invokedDirectly) {
  runProvisionOwner(process.argv.slice(2)).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
