import { chmodSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { hashPassword } from "better-auth/crypto";

import {
  assertInteractiveTerminal,
  defaultPromptIO,
  promptForNewPassword,
} from "./prompt-password";
import {
  databaseNameFor,
  executeFile,
  executeFileArgs,
  parseRemoteArgs,
  queryRemoteRows,
  usageFor,
  type RemoteTarget,
} from "./remote-d1";

/**
 * Creates the one owner account on a remote D1 database.
 *
 * ## Why this is separate from the content seed
 *
 * The content seed may be run repeatedly and is inert if it meets rows it did
 * not write. A password cannot be: it is a credential, it is hashed on purpose,
 * and re-running it would either fail (good) or silently mint a second way into
 * the account (not good). So credentials get their own script, their own
 * refusal, and their own handling of the secret.
 *
 * ## The refusal
 *
 * Before anything is generated at apply time, the script asks the target
 * database whether *any* user row exists, and stops if it does — with the
 * addresses it found, so the operator can see which account is already there.
 * The application ships with sign-up disabled and a single owner role, so one
 * row is the whole expected state and a second row is never a thing to create
 * quietly.
 *
 * The generated SQL carries no `ON CONFLICT` clause either. If a row appears
 * between the check and the apply, the insert violates the unique email index,
 * wrangler's file import fails, and the database is left as it was — wrangler
 * reports a failed import as a rollback. The check gives the friendly message;
 * the database gives the guarantee.
 *
 * ## The password
 *
 * Read once, from a masked interactive prompt with a confirmation
 * (`scripts/prompt-password.ts`), never from an argument, an environment
 * variable, a file, or `.dev.vars`: this project lives in a synced directory,
 * and a password written there is a password in every backup of it. What
 * reaches disk is the `hashPassword` output — the same hashing Better Auth
 * verifies at sign-in — so the plaintext exists only in the process that
 * prompted for it.
 *
 * The hash is written to a uniquely named directory under the OS temporary
 * directory (outside the project, outside the sync), with the most restrictive
 * permissions the platform supports, and the directory is removed in a
 * `finally` block whether the apply succeeds, fails, or throws. Printed output
 * — dry run included — shows the statements with the hash replaced by a
 * placeholder, and any wrangler error is scrubbed of the real hash before it
 * reaches the terminal.
 *
 * ## Usage
 *
 * ```bash
 * npm run db:provision:owner -- --env preview     # print redacted SQL, execute nothing
 * npm run db:provision:owner -- --env preview --apply   # prompts twice, then applies
 * npm run db:provision:owner -- --env production --apply
 * ```
 */

/**
 * Mirrors `minPasswordLength` in `src/auth.ts`.
 *
 * A shorter password would be hashed happily here and then refused by Better
 * Auth at sign-in, so the check moves to where the mistake is cheapest to fix.
 * `tests/unit/remote-init.test.ts` asserts the two numbers stay equal.
 */
export const MIN_PASSWORD_LENGTH = 12;

export interface OwnerProvisioning {
  email: string;
  name: string;
}

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** The pre-flight question: is there already an account on this database? */
export function existingOwnerCommand(): string {
  return "SELECT email FROM user ORDER BY created_at";
}

/** Wraps a refusal so a script run exits non-zero with a readable reason. */
export class OwnerAlreadyExistsError extends Error {
  constructor(target: RemoteTarget, emails: string[]) {
    super(
      [
        `Refusing to provision the ${target} database: it already has ${emails.length} account(s):`,
        ...emails.map((email) => `  - ${email}`),
        "",
        "Nothing was written. If this is the owner's account, the database is already",
        "provisioned; sign in instead. Creating a second account is not a supported",
        "state, so this script will not do it.",
      ].join("\n"),
    );
    this.name = "OwnerAlreadyExistsError";
  }
}

/** The placeholder printed wherever a real hash would appear. */
export const REDACTED_PLACEHOLDER = "<redacted: password hash, read interactively at apply time>";

/** The name of the file wrangler imports; it only ever exists under `os.tmpdir()`. */
export const OWNER_SQL_FILE = "owner-provision.sql";

const SQL_HEADER = [
  `-- Generated by scripts/provision-owner.ts. Do not edit by hand.`,
  `-- Contains a password hash, never the password itself.`,
  `-- The account is created only if no user row exists yet; the script checked first.`,
  `-- The file lives in an OS temporary directory, is deleted after the run (even on`,
  `-- failure), and is never written inside the project directory.`,
  `-- Apply with: wrangler d1 execute <database> --remote --file <this file>`,
].join("\n");

/**
 * The three statements that create the account, given an already-hashed
 * password (or a placeholder, for the review copy).
 *
 * Deliberately without `ON CONFLICT`: every one of them must succeed or none of
 * them may run, and wrangler's import executes the file as a single unit.
 */
export function ownerStatements(
  email: string,
  name: string,
  passwordHash: string,
  userId: string = crypto.randomUUID(),
): string[] {
  return [
    `INSERT INTO user (id, name, email, email_verified, image, created_at, updated_at)`,
    `  VALUES (${sqlString(userId)}, ${sqlString(name)}, ${sqlString(email)}, 1, NULL, unixepoch(), unixepoch());`,
    ``,
    `INSERT INTO account (id, user_id, account_id, provider_id, password, created_at, updated_at)`,
    `  VALUES (${sqlString(crypto.randomUUID())}, ${sqlString(userId)}, ${sqlString(userId)}, 'credential', ${sqlString(passwordHash)}, unixepoch(), unixepoch());`,
    ``,
    `INSERT INTO profiles (id, role, display_name, created_at, updated_at)`,
    `  VALUES (${sqlString(userId)}, 'owner', ${sqlString(name)}, unixepoch(), unixepoch());`,
  ];
}

function assembleOwnerSql(statements: string[]): string {
  return `${SQL_HEADER}\n\n${statements.join("\n")}\n`;
}

/**
 * The real SQL: hashes the password and assembles the statements around it.
 *
 * The result is written only to the temporary file the apply executes; nothing
 * in this module prints it.
 */
export async function buildOwnerSql(owner: OwnerProvisioning & { password: string }): Promise<string> {
  const passwordHash = await hashPassword(owner.password);
  return assembleOwnerSql(ownerStatements(owner.email, owner.name, passwordHash));
}

/**
 * The review copy shown by a dry run: same statements, placeholder credential.
 *
 * A dry run has no password (it prompts for nothing), so this is not the SQL
 * that will run — it is the shape of it. It contains no hash to leak, which is
 * why it is the only copy that may be printed.
 */
export function renderOwnerSqlForReview(owner: OwnerProvisioning): string {
  return assembleOwnerSql(
    ownerStatements(owner.email, owner.name, REDACTED_PLACEHOLDER, "<generated at apply time>"),
  );
}

/**
 * Removes every occurrence of the given secrets from text headed for a
 * terminal. Used on wrangler's output, which quotes file contents when an
 * import fails.
 */
export function redactSecrets(text: string, secrets: Array<string | undefined>): string {
  let out = text;
  for (const secret of secrets) {
    if (secret) {
      out = out.split(secret).join(REDACTED_PLACEHOLDER);
    }
  }
  return out;
}

/**
 * Writes the SQL to a fresh directory under the OS temporary directory, runs
 * `apply`, and removes the directory on every exit path.
 *
 * `os.tmpdir()` is deliberately not the project directory: this repository
 * lives inside a synced folder, and generated credential material must not
 * appear in a sync or a backup of it. The directory comes from `mkdtemp`, which
 * creates it with mode `0700` where that is meaningful; the file is written
 * with mode `0600` and re-chmodded where the platform supports it. The
 * `finally` block covers the failure paths too — an apply that throws still
 * leaves nothing behind.
 */
export function withTemporarySqlFile<T>(
  fileName: string,
  sql: string,
  apply: (filePath: string) => T,
): T {
  const directory = mkdtempSync(path.join(os.tmpdir(), "resta-pescado-owner-"));
  try {
    const filePath = path.join(directory, fileName);
    writeFileSync(filePath, sql, { encoding: "utf8", mode: 0o600 });
    try {
      chmodSync(filePath, 0o600);
    } catch {
      // Windows does not implement POSIX modes; the directory is already
      // user-only where the concept exists. "Where supported" is the contract.
    }
    return apply(filePath);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
}

/**
 * Returns a warning when a password variable is present in the environment —
 * for example in `.dev.vars`, which lives in this synced project directory.
 *
 * The value is never echoed; the warning only says that this script ignores it
 * and that the local seed and the end-to-end suite are the legitimate users of
 * that variable. Returns `null` when the variable is absent, so tests can
 * assert on the decision rather than on console output.
 */
export function warnIfPasswordIsInEnvironment(
  env: Record<string, string | undefined>,
): string | null {
  const value = env.OWNER_PASSWORD;
  if (!value) {
    return null;
  }
  return [
    "OWNER_PASSWORD is set in this environment (typically .dev.vars).",
    "This script never reads it: the password is typed at a masked prompt instead,",
    "and its value is not printed or used. The local seed and the end-to-end suite",
    "are the commands that need that variable; nothing about remote provisioning does.",
  ].join(" ");
}

export function assertPasswordUsable(password: string): void {
  if (password.length < MIN_PASSWORD_LENGTH) {
    throw new Error(
      `The password you entered is ${password.length} characters; Better Auth refuses anything shorter than ${MIN_PASSWORD_LENGTH}. Run the command again and choose a longer password.`,
    );
  }
}

/** What `--help` prints, shared by both run modes. */
function helpText(): string {
  return usageFor("npm run db:provision:owner --", [
    "Requires OWNER_EMAIL (and optionally OWNER_NAME) in the environment or .dev.vars.",
    "The password is read from a masked interactive prompt when --apply runs;",
    "it is never accepted from an argument, an environment variable, or a file.",
    "The apply writes its SQL to a uniquely named directory under the OS temporary",
    "directory, with restrictive permissions, and deletes it when the run ends.",
    "Nothing is executed without --apply.",
  ]);
}

export async function runProvisionOwner(argv: string[]): Promise<void> {
  const args = parseRemoteArgs(argv);

  if (args.help) {
    console.log(helpText());
    return;
  }

  if (args.target === null) {
    console.error(usageFor("npm run db:provision:owner --", ["--env is required; there is no default."]));
    process.exitCode = 1;
    return;
  }

  const target: RemoteTarget = args.target;
  const databaseName = databaseNameFor(target);

  const { readEnvFile, requireEnv } = await import("./env");
  readEnvFile();
  const email = requireEnv("OWNER_EMAIL");
  const name = process.env.OWNER_NAME ?? "Propriétaire";

  const environmentWarning = warnIfPasswordIsInEnvironment(process.env);
  if (environmentWarning) {
    console.warn(environmentWarning);
  }

  if (!args.apply) {
    console.log(renderOwnerSqlForReview({ email, name }));
    console.log("Dry run: nothing was executed, no password was requested, and no file was written.");
    console.log(
      "With --apply the password is read from a masked prompt (typed twice), the real SQL is",
      `written to a temporary directory under ${os.tmpdir()}, executed against the ${target}`,
      "database, and deleted afterwards — including when the apply fails.",
    );
    console.log(`The ${target} database will first be checked for an existing account, and the`);
    console.log("script refuses to continue if any is found.");
    console.log("The apply runs this command, with the temporary file path filled in:");
    console.log(
      `  node node_modules/wrangler/bin/wrangler.js ${executeFileArgs({
        target,
        databaseName,
        filePath: path.join(os.tmpdir(), "resta-pescado-owner-<random>", OWNER_SQL_FILE),
      }).join(" ")}`,
    );
    return;
  }

  // The refusal comes first: an apply that would be refused learns that before
  // it is asked for a secret, and no interactive step can get in front of it.
  const rows = queryRemoteRows({ target, databaseName, command: existingOwnerCommand() });
  if (rows.length > 0) {
    throw new OwnerAlreadyExistsError(
      target,
      rows.map((row) => String(row.email ?? "(unknown)")),
    );
  }

  // Only then a terminal: a non-interactive session has no way to supply the
  // password, and there is no point prompting when the answer was "stop".
  assertInteractiveTerminal(defaultPromptIO());

  const password = await promptForNewPassword(defaultPromptIO());
  assertPasswordUsable(password);
  const passwordHash = await hashPassword(password);
  const sql = assembleOwnerSql(ownerStatements(email, name, passwordHash));

  console.log(`Applying owner SQL to the ${target} database (${databaseName})...`);
  console.log(`The SQL file exists only under ${os.tmpdir()} and is deleted when this command ends.`);

  try {
    withTemporarySqlFile(OWNER_SQL_FILE, sql, (filePath) => {
      try {
        executeFile({ target, databaseName, filePath });
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        throw new Error(redactSecrets(message, [passwordHash]));
      }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    // The temporary file is already gone (finally above); make sure the
    // terminal never sees a hash either.
    throw new Error(redactSecrets(message, [passwordHash]));
  }

  console.log(`Owner account ${email} created. It is the only account on this database.`);
}

const invokedDirectly =
  process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/provision-owner.ts") === true;

if (invokedDirectly) {
  runProvisionOwner(process.argv.slice(2)).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
