import { APPROVED_CATEGORIES, APPROVED_MENU } from "./approved-menu";
import {
  databaseNameFor,
  executeFile,
  executeFileArgs,
  parseRemoteArgs,
  usageFor,
  writeSqlFile,
  type RemoteTarget,
} from "./remote-d1";
import { SEED_DELIVERY, SEED_SETTINGS } from "./site-settings";
import { listBundledGalleryImages } from "../src/lib/gallery-images";

/**
 * Initializes site content on a remote D1 database: the approved categories and
 * dishes, the confirmed site settings, and the bundled gallery manifest.
 *
 * ## Non-destructive by construction
 *
 * Every statement is `INSERT ... ON CONFLICT DO NOTHING`. Rows that already
 * exist are left exactly as they are, which means:
 *
 * - Running it twice changes nothing, so a repeated run is never a second
 *   chance to damage anything.
 * - A dish the owner renamed, repriced or hid through the dashboard survives,
 *   because an existing row is never updated.
 * - A dish the owner *added* survives too: there is no delete here at all, so
 *   nothing that is not in the approved list is ever removed.
 *
 * The local seed (`scripts/seed-local.ts`) is deliberately different — it
 * upserts, and can delete under `SEED_ALLOW_DELETE=1`, because a development
 * database is meant to be resettable. That power stays behind the local guard in
 * `scripts/local-db-guard.ts` and is never exported to a remote path.
 *
 * ## What it does not do
 *
 * - **No owner account.** Credentials are `scripts/provision-owner.ts`, which
 *   checks for an existing account first. Content and passwords do not belong in
 *   the same file.
 * - **No migrations.** The schema comes from
 *   `wrangler d1 migrations apply <db> --remote`; this script assumes it.
 * - **No uploaded objects.** Bundled photographs ship as repository assets, and dish
 *   photographs are only ever owner uploads, so there is nothing to seed into the
 *   media store.
 *
 * ## Usage
 *
 * ```bash
 * npm run db:seed:remote -- --env preview     # print the SQL, execute nothing
 * npm run db:seed:remote -- --env preview --apply
 * npm run db:seed:remote -- --env production --apply
 * ```
 */

/** Quotes a string for SQLite, doubling any apostrophe it contains. */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlNullable(value: string | null): string {
  return value === null ? "NULL" : sqlString(value);
}

function sqlBool(value: boolean): number {
  return value ? 1 : 0;
}

const HEADER = `-- Generated by scripts/seed-remote.ts. Do not edit by hand.
-- Insert-only: every statement is ON CONFLICT DO NOTHING, so rows that already
-- exist -- including everything the owner has changed through the dashboard --
-- are left untouched. Safe to run again; a second run changes nothing.
-- Apply with: wrangler d1 execute <database> --remote --file <this file>
`;

/**
 * The complete content SQL for a database that has already been migrated.
 *
 * Column lists mirror `scripts/seed-local.ts` on purpose: the two writers must
 * agree on the shape of a row, and a schema change is a change to both.
 */
export function buildContentSql(): string {
  const statements: string[] = [HEADER];

  statements.push(
    [
      "INSERT INTO menu_categories",
      "  (id, name_fr, slug, sort_order, is_visible, created_at, updated_at) VALUES",
      APPROVED_CATEGORIES.map(
        (category, index) =>
          `  (${sqlString(category.id)}, ${sqlString(category.nameFr)}, ${sqlString(category.slug)}, ${index + 1}, 1, unixepoch(), unixepoch())`,
      ).join(",\n"),
      "ON CONFLICT DO NOTHING;",
    ].join("\n"),
  );

  const itemRows: string[] = [];
  for (const group of APPROVED_MENU) {
    for (const [index, item] of group.items.entries()) {
      itemRows.push(
        `  (${sqlString(item.id)}, ${sqlString(group.categoryId)}, ${sqlString(item.nameFr)}, NULL, ${item.priceDa}, NULL, ${sqlNullable(item.fishReferenceSlug ?? null)}, 0, 1, ${index + 1}, unixepoch(), unixepoch())`,
      );
    }
  }
  statements.push(
    [
      "INSERT INTO menu_items",
      "  (id, category_id, name_fr, description_fr, price_da, image_key, fish_reference_slug, is_featured, is_visible, sort_order, created_at, updated_at) VALUES",
      itemRows.join(",\n"),
      "ON CONFLICT DO NOTHING;",
    ].join("\n"),
  );

  statements.push(
    [
      "INSERT INTO site_settings",
      "  (id, restaurant_name_fr, phone_fr, address_fr, maps_url, hours_fr, family_note_fr, hero_title_fr, hero_subtitle_fr, delivery_enabled, delivery_zones_text_fr, delivery_fee_text_fr, delivery_minimum_order_text_fr, delivery_hours_fr, pickup_text_fr, created_at, updated_at) VALUES",
      `  ('singleton', 'Resta Pescado', ${sqlString(SEED_SETTINGS.phoneFr)}, ${sqlNullable(SEED_SETTINGS.addressFr)}, ${sqlString(SEED_SETTINGS.mapsUrl)}, ${sqlString(SEED_SETTINGS.hoursFr)}, ${sqlString(SEED_SETTINGS.familyNoteFr)}, ${sqlString(SEED_SETTINGS.heroTitleFr)}, ${sqlString(SEED_SETTINGS.heroSubtitleFr)}, ${sqlBool(SEED_DELIVERY.enabled)}, ${sqlString(SEED_DELIVERY.zones)}, ${sqlString(SEED_DELIVERY.fee)}, ${sqlString(SEED_DELIVERY.minimumOrder)}, ${sqlString(SEED_DELIVERY.hours)}, ${sqlString(SEED_DELIVERY.ordering)}, unixepoch(), unixepoch())`,
      "ON CONFLICT DO NOTHING;",
    ].join("\n"),
  );

  const bundledRows = listBundledGalleryImages().map(
    (image, index) =>
      `  (${sqlString(image.slug)}, ${sqlString(image.altFr)}, NULL, ${index + 1}, 1, unixepoch(), unixepoch(), 1)`,
  );
  statements.push(
    [
      "INSERT INTO bundled_gallery_images",
      "  (slug, alt_text_fr, caption_fr, sort_order, is_visible, created_at, updated_at, version) VALUES",
      bundledRows.join(",\n"),
      "ON CONFLICT DO NOTHING;",
    ].join("\n"),
  );

  return `${statements.join("\n\n")}\n`;
}

/** The name of the generated file, kept next to the wrangler state it serves. */
export const CONTENT_SQL_FILE = "remote-content.sql";

export async function runSeedRemote(argv: string[]): Promise<void> {
  const args = parseRemoteArgs(argv);

  if (args.help) {
    console.log(
      usageFor("npm run db:seed:remote --", [
        "The apply writes its SQL under the gitignored .wrangler/ (remote-content.sql)",
        "and leaves it there for review or a manual re-run.",
        "Nothing is executed without --apply.",
      ]),
    );
    return;
  }

  if (args.target === null) {
    console.error(usageFor("npm run db:seed:remote --", ["--env is required; there is no default."]));
    process.exitCode = 1;
    return;
  }

  const target: RemoteTarget = args.target;
  const databaseName = databaseNameFor(target);
  const sql = buildContentSql();
  const filePath = writeSqlFile(CONTENT_SQL_FILE, sql);

  if (!args.apply) {
    console.log(sql);
    console.log(`Written to ${filePath}. Nothing was executed.`);
    console.log("To apply it to the " + target + " database:");
    console.log(
      `  node node_modules/wrangler/bin/wrangler.js ${executeFileArgs({ target, databaseName, filePath }).join(" ")}`,
    );
    return;
  }

  console.log(`Applying ${filePath} to the ${target} database (${databaseName})...`);
  executeFile({ target, databaseName, filePath });
  console.log("Done. Existing rows were left untouched; run it again and nothing changes.");
}

const invokedDirectly =
  process.argv[1]?.replace(/\\/g, "/").endsWith("scripts/seed-remote.ts") === true;

if (invokedDirectly) {
  runSeedRemote(process.argv.slice(2)).catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
