import Database from "better-sqlite3";
import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { describe, expect, it } from "vitest";

import { applyMigrations } from "../../scripts/migrate";
import * as schema from "../../src/db/schema";
import {
  getAdminMenu,
  getPublicMenu,
  getMenuItem,
  recordAuditLog,
  updateMenuItemImageKey,
  updateMenuItemPrice,
  findAuditLogs,
  listAuditLogs,
} from "../../src/db/repositories/menu";
import {
  consumeRateLimit,
  findOwnerProfile,
  pruneRateLimitCounters,
} from "../../src/db/repositories/admin";

/**
 * Repository tests run against real SQLite with the real migration files, so the
 * schema, the constraints, and the queries are all exercised together. The
 * production driver is D1; D1 is SQLite, so the SQL generated by Drizzle is the
 * same, and these tests would not catch a D1-specific dialect issue on their
 * own. That gap is covered by the Playwright suite, which runs inside workerd.
 */

type TestDatabase = ReturnType<typeof createDatabase>;

function createDatabase() {
  const native = new Database(":memory:");
  native.pragma("foreign_keys = ON");
  applyMigrations(native);
  const db = drizzle(native, { schema });
  return { db, native };
}

function seedFixture(db: TestDatabase["db"]): { categoryId: string; itemId: string } {
  const categoryId = "cat-1";
  const itemId = "item-1";
  // Fixed timestamps rather than the `unixepoch()` default, so the ordering
  // assertions below do not depend on when the suite runs.
  const seededAt = new Date("2026-01-15T10:00:00Z");

  db.insert(schema.menuCategories)
    .values({
      id: categoryId,
      nameFr: "Poissons",
      slug: "poissons",
      sortOrder: 1,
      isVisible: true,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuCategories)
    .values({
      id: "cat-hidden",
      nameFr: "Caché",
      slug: "cache",
      sortOrder: 2,
      isVisible: false,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuItems)
    .values({
      id: itemId,
      categoryId,
      nameFr: "Dorade grillée",
      descriptionFr: "Entière.",
      priceDa: 900,
      isFeatured: true,
      isVisible: true,
      sortOrder: 1,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuItems)
    .values({
      id: "item-hidden",
      categoryId,
      nameFr: "Plat caché",
      priceDa: 500,
      isVisible: false,
      sortOrder: 2,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.user)
    .values({
      id: "user-1",
      name: "Owner",
      email: "owner@test.local",
      emailVerified: true,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.profiles)
    .values({ id: "user-1", role: "owner", displayName: "Owner", createdAt: seededAt, updatedAt: seededAt })
    .run();

  return { categoryId, itemId };
}

describe("menu repository", () => {
  it("returns only visible categories and items, ordered", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      const menu = await getPublicMenu(db);

      expect(menu.categories).toHaveLength(1);
      expect(menu.categories[0]?.slug).toBe("poissons");
      expect(menu.categories[0]?.items.map((item) => item.id)).toEqual(["item-1"]);
      expect(menu.categories[0]?.items[0]?.priceDa).toBe(900);
    } finally {
      native.close();
    }
  });

  it("returns hidden rows to the admin view", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      const menu = await getAdminMenu(db);

      expect(menu.categories.map((category) => category.id)).toEqual(["cat-1", "cat-hidden"]);
      expect(menu.categories[0]?.items.map((item) => item.id)).toEqual(["item-1", "item-hidden"]);
    } finally {
      native.close();
    }
  });

  it("returns an empty menu rather than throwing when nothing is seeded", async () => {
    const { db, native } = createDatabase();
    try {
      const menu = await getPublicMenu(db);
      expect(menu).toEqual({ categories: [] });
    } finally {
      native.close();
    }
  });

  it("persists a new price and bumps updated_at", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);
      const before = await getMenuItem(db, itemId);

      const updated = await updateMenuItemPrice(db, itemId, 950, new Date("2026-02-01T12:00:00Z"));

      expect(updated?.priceDa).toBe(950);
      const after = await getMenuItem(db, itemId);
      expect(after?.priceDa).toBe(950);
      expect(after?.updatedAt.getTime()).toBeGreaterThan(before?.updatedAt.getTime() ?? 0);
    } finally {
      native.close();
    }
  });

  it("returns null for an unknown item id", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      expect(await updateMenuItemPrice(db, "does-not-exist", 100)).toBeNull();
    } finally {
      native.close();
    }
  });

  it("rejects a non-positive price at the database level", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);
      expect(() =>
        db.update(schema.menuItems).set({ priceDa: 0 }).where(eqId(itemId)).run(),
      ).toThrow();
      expect(() =>
        db.update(schema.menuItems).set({ priceDa: -5 }).where(eqId(itemId)).run(),
      ).toThrow();
    } finally {
      native.close();
    }
  });

  it("replaces the image key and can clear it", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);

      const withImage = await updateMenuItemImageKey(db, itemId, "menu/2026/abc.png");
      expect(withImage?.imageKey).toBe("menu/2026/abc.png");

      const cleared = await updateMenuItemImageKey(db, itemId, null);
      expect(cleared?.imageKey).toBeNull();
    } finally {
      native.close();
    }
  });
});

function eqId(id: string) {
  return eq(schema.menuItems.id, id);
}

describe("audit repository", () => {
  it("records one row per action with JSON metadata", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);

      await recordAuditLog(db, {
        actorId: "user-1",
        action: "menu_item.price_updated",
        entityType: "menu_item",
        entityId: itemId,
        metadata: { from: 900, to: 950 },
      });
      await recordAuditLog(db, {
        actorId: "user-1",
        action: "menu_item.image_replaced",
        entityType: "menu_item",
        entityId: itemId,
        metadata: { from: null, to: "menu/2026/x.png" },
      });

      const all = await listAuditLogs(db);
      expect(all).toHaveLength(2);
      expect(all.map((log) => log.action).sort()).toEqual([
        "menu_item.image_replaced",
        "menu_item.price_updated",
      ]);

      const parsed = JSON.parse(all[0]?.metadata ?? "{}") as Record<string, unknown>;
      expect(Object.keys(parsed).length).toBeGreaterThan(0);

      const forItem = await findAuditLogs(db, "menu_item", itemId);
      expect(forItem).toHaveLength(2);
    } finally {
      native.close();
    }
  });

  it("stores a null actor for a pre-auth attempt", async () => {
    const { db, native } = createDatabase();
    try {
      await recordAuditLog(db, {
        actorId: null,
        action: "auth.login_failed",
        entityType: "session",
        entityId: "unknown",
      });

      const [log] = await listAuditLogs(db);
      expect(log?.actorId).toBeNull();
    } finally {
      native.close();
    }
  });
});

describe("owner authorization query", () => {
  it("returns the profile for an owner", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      const profile = await findOwnerProfile(db, "user-1");
      expect(profile?.role).toBe("owner");
    } finally {
      native.close();
    }
  });

  it("returns null for an unknown user", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      expect(await findOwnerProfile(db, "nobody")).toBeNull();
    } finally {
      native.close();
    }
  });

  it("returns null when the profile row is missing even if the user exists", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      db.delete(schema.profiles).run();
      expect(await findOwnerProfile(db, "user-1")).toBeNull();
    } finally {
      native.close();
    }
  });
});

describe("rate limiter", () => {
  it("allows up to the limit then denies within the window", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 3, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      const first = await consumeRateLimit(db, "user-1", rule, now);
      const second = await consumeRateLimit(db, "user-1", rule, now);
      const third = await consumeRateLimit(db, "user-1", rule, now);
      const fourth = await consumeRateLimit(db, "user-1", rule, now);

      expect(first.allowed).toBe(true);
      expect(second.allowed).toBe(true);
      expect(third.allowed).toBe(true);
      expect(fourth.allowed).toBe(false);
      expect(third.remaining).toBe(0);
      expect(fourth.retryAfterSeconds).toBeGreaterThan(0);
    } finally {
      native.close();
    }
  });

  it("resets on the next window", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 1, windowSeconds: 60 };
      const start = new Date("2026-01-15T10:00:00Z");

      expect((await consumeRateLimit(db, "user-1", rule, start)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", rule, start)).allowed).toBe(false);

      const nextWindow = new Date("2026-01-15T10:01:00Z");
      expect((await consumeRateLimit(db, "user-1", rule, nextWindow)).allowed).toBe(true);
    } finally {
      native.close();
    }
  });

  it("keys on identity and action independently", async () => {
    const { db, native } = createDatabase();
    try {
      const priceRule = { action: "menu_item.update_price", limit: 1, windowSeconds: 60 };
      const imageRule = { action: "menu_item.replace_image", limit: 1, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      expect((await consumeRateLimit(db, "user-1", priceRule, now)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", priceRule, now)).allowed).toBe(false);

      // A different action, and a different identity, are both unaffected.
      expect((await consumeRateLimit(db, "user-1", imageRule, now)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-2", priceRule, now)).allowed).toBe(true);
    } finally {
      native.close();
    }
  });

  it("prunes counters older than a day", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 5, windowSeconds: 60 };
      await consumeRateLimit(db, "user-1", rule, new Date("2026-01-10T10:00:00Z"));

      await pruneRateLimitCounters(db, new Date("2026-01-15T10:00:00Z"));
      const after = await consumeRateLimit(db, "user-1", rule, new Date("2026-01-15T10:00:00Z"));
      expect(after.allowed).toBe(true);
    } finally {
      native.close();
    }
  });
});
