import Database from "better-sqlite3";
import { eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { describe, expect, it } from "vitest";

import { applyMigrations } from "../../scripts/migrate";
import * as schema from "../../src/db/schema";
import {
  getAdminMenu,
  getPublicMenu,
  getMenuItem,
  recordAuditLog,
  updateMenuItemImageKey,
  updateMenuItemImageKeyWithAudit,
  updateMenuItemPrice,
  updateMenuItemPriceWithAudit,
  findAuditLogs,
  listAuditLogs,
} from "../../src/db/repositories/menu";
import {
  consumeRateLimit,
  findOwnerProfile,
  pruneRateLimitCounters,
} from "../../src/db/repositories/admin";

/**
 * Repository tests run against real SQLite with the real migration files, so the
 * schema, the constraints, and the queries are all exercised together. The
 * production driver is D1; D1 is SQLite, so the SQL generated by Drizzle is the
 * same, and these tests would not catch a D1-specific dialect issue on their
 * own. That gap is covered by the Playwright suite, which runs inside workerd.
 */

type TestDatabase = ReturnType<typeof createDatabase>;

function createDatabase() {
  const native = new Database(":memory:");
  native.pragma("foreign_keys = ON");
  applyMigrations(native);
  const db = drizzle(native, { schema });
  return { db, native };
}

function seedFixture(db: TestDatabase["db"]): { categoryId: string; itemId: string } {
  const categoryId = "cat-1";
  const itemId = "item-1";
  // Fixed timestamps rather than the `unixepoch()` default, so the ordering
  // assertions below do not depend on when the suite runs.
  const seededAt = new Date("2026-01-15T10:00:00Z");

  db.insert(schema.menuCategories)
    .values({
      id: categoryId,
      nameFr: "Poissons",
      slug: "poissons",
      sortOrder: 1,
      isVisible: true,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuCategories)
    .values({
      id: "cat-hidden",
      nameFr: "Caché",
      slug: "cache",
      sortOrder: 2,
      isVisible: false,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuItems)
    .values({
      id: itemId,
      categoryId,
      nameFr: "Dorade grillée",
      descriptionFr: "Entière.",
      priceDa: 900,
      isFeatured: true,
      isVisible: true,
      sortOrder: 1,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.menuItems)
    .values({
      id: "item-hidden",
      categoryId,
      nameFr: "Plat caché",
      priceDa: 500,
      isVisible: false,
      sortOrder: 2,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.user)
    .values({
      id: "user-1",
      name: "Owner",
      email: "owner@test.local",
      emailVerified: true,
      createdAt: seededAt,
      updatedAt: seededAt,
    })
    .run();
  db.insert(schema.profiles)
    .values({ id: "user-1", role: "owner", displayName: "Owner", createdAt: seededAt, updatedAt: seededAt })
    .run();

  return { categoryId, itemId };
}

describe("menu repository", () => {
  it("returns only visible categories and items, ordered", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      const menu = await getPublicMenu(db);

      expect(menu.categories).toHaveLength(1);
      expect(menu.categories[0]?.slug).toBe("poissons");
      expect(menu.categories[0]?.items.map((item) => item.id)).toEqual(["item-1"]);
      expect(menu.categories[0]?.items[0]?.priceDa).toBe(900);
    } finally {
      native.close();
    }
  });

  it("returns hidden rows to the admin view", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      const menu = await getAdminMenu(db);

      expect(menu.categories.map((category) => category.id)).toEqual(["cat-1", "cat-hidden"]);
      expect(menu.categories[0]?.items.map((item) => item.id)).toEqual(["item-1", "item-hidden"]);
    } finally {
      native.close();
    }
  });

  it("returns an empty menu rather than throwing when nothing is seeded", async () => {
    const { db, native } = createDatabase();
    try {
      const menu = await getPublicMenu(db);
      expect(menu).toEqual({ categories: [] });
    } finally {
      native.close();
    }
  });

  it("persists a new price and bumps updated_at", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);
      const before = await getMenuItem(db, itemId);

      const updated = await updateMenuItemPrice(db, itemId, 950, new Date("2026-02-01T12:00:00Z"));

      expect(updated?.priceDa).toBe(950);
      const after = await getMenuItem(db, itemId);
      expect(after?.priceDa).toBe(950);
      expect(after?.updatedAt.getTime()).toBeGreaterThan(before?.updatedAt.getTime() ?? 0);
    } finally {
      native.close();
    }
  });

  it("returns null for an unknown item id", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      expect(await updateMenuItemPrice(db, "does-not-exist", 100)).toBeNull();
    } finally {
      native.close();
    }
  });

  it("rejects a non-positive price at the database level", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);
      expect(() =>
        db.update(schema.menuItems).set({ priceDa: 0 }).where(eqId(itemId)).run(),
      ).toThrow();
      expect(() =>
        db.update(schema.menuItems).set({ priceDa: -5 }).where(eqId(itemId)).run(),
      ).toThrow();
    } finally {
      native.close();
    }
  });

  it("replaces the image key and can clear it", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);

      const withImage = await updateMenuItemImageKey(db, itemId, "menu/2026/abc.png");
      expect(withImage?.imageKey).toBe("menu/2026/abc.png");

      const cleared = await updateMenuItemImageKey(db, itemId, null);
      expect(cleared?.imageKey).toBeNull();
    } finally {
      native.close();
    }
  });
});

describe("atomic menu writes", () => {
  /**
   * Both failure directions are covered, because they are different bugs.
   *
   * A bad price is the update failing, which proves the audit insert does not
   * survive on its own. A bad actor is the audit failing, which proves the
   * dish does not move without its trail. A batch that only ever rolls back in
   * one of those directions is still broken.
   */
  const badPrice = { menuItemId: "item-1", priceDa: 0 };

  function priceAudit(actorId: string) {
    return {
      actorId,
      action: "menu_item.price_updated",
      entityType: "menu_item",
      entityId: "item-1",
      metadata: { from: 900, to: 1000 },
    };
  }

  it("writes the price and its audit row together", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      await updateMenuItemPriceWithAudit(db, {
        menuItemId: "item-1",
        priceDa: 1000,
        audit: priceAudit("user-1"),
      });

      const item = await getMenuItem(db, "item-1");
      expect(item?.priceDa).toBe(1000);
      const audit = await findAuditLogs(db, "menu_item", "item-1");
      expect(audit).toHaveLength(1);
      expect(audit[0]!.action).toBe("menu_item.price_updated");
      expect(JSON.parse(audit[0]!.metadata)).toEqual({ from: 900, to: 1000 });
    } finally {
      native.close();
    }
  });

  it("rolls the audit row back when the price violates its constraint", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      await expect(
        updateMenuItemPriceWithAudit(db, { ...badPrice, audit: priceAudit("user-1") }),
      ).rejects.toThrow();

      // The audit insert would have succeeded on its own, so finding a row here
      // means the batch is not atomic.
      expect(await findAuditLogs(db, "menu_item", "item-1")).toHaveLength(0);
      const item = await getMenuItem(db, "item-1");
      expect(item?.priceDa).toBe(900);
    } finally {
      native.close();
    }
  });

  it("rolls the price back when the audit insert violates its foreign key", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      // `user-ghost` is not in the `user` table and foreign keys are on, so the
      // audit insert fails while the update would otherwise have succeeded.
      await expect(
        updateMenuItemPriceWithAudit(db, {
          menuItemId: "item-1",
          priceDa: 1000,
          audit: priceAudit("user-ghost"),
        }),
      ).rejects.toThrow();

      // The dangerous half: a price the owner never agreed to, with no trail.
      const item = await getMenuItem(db, "item-1");
      expect(item?.priceDa).toBe(900);
      expect(await findAuditLogs(db, "menu_item", "item-1")).toHaveLength(0);
    } finally {
      native.close();
    }
  });

  it("rejects rather than leaving a trail for a dish that does not exist", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      await expect(
        updateMenuItemPriceWithAudit(db, {
          menuItemId: "item-missing",
          priceDa: 1000,
          audit: { ...priceAudit("user-1"), entityId: "item-missing" },
        }),
      ).rejects.toThrow();

      expect(await findAuditLogs(db, "menu_item", "item-missing")).toHaveLength(0);
    } finally {
      native.close();
    }
  });

  it("writes the image key and its audit row together", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);

      await updateMenuItemImageKeyWithAudit(db, {
        menuItemId: "item-1",
        imageKey: "menu/2026/new.png",
        audit: {
          actorId: "user-1",
          action: "menu_item.image_replaced",
          entityType: "menu_item",
          entityId: "item-1",
          metadata: { from: null, to: "menu/2026/new.png" },
        },
      });

      const item = await getMenuItem(db, "item-1");
      expect(item?.imageKey).toBe("menu/2026/new.png");
      expect(await findAuditLogs(db, "menu_item", "item-1")).toHaveLength(1);
    } finally {
      native.close();
    }
  });

  it("leaves the previous image key in place when the audit insert fails", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      await updateMenuItemImageKey(db, "item-1", "menu/2026/original.png");

      await expect(
        updateMenuItemImageKeyWithAudit(db, {
          menuItemId: "item-1",
          imageKey: "menu/2026/replacement.png",
          audit: {
            actorId: "user-ghost",
            action: "menu_item.image_replaced",
            entityType: "menu_item",
            entityId: "item-1",
            metadata: {},
          },
        }),
      ).rejects.toThrow();

      // This is the assertion that justifies the R2 compensation in the action:
      // the database still points at the original object, so that object must not
      // have been deleted.
      const item = await getMenuItem(db, "item-1");
      expect(item?.imageKey).toBe("menu/2026/original.png");
      expect(await findAuditLogs(db, "menu_item", "item-1")).toHaveLength(0);
    } finally {
      native.close();
    }
  });
});

/**
 * Reads a rate-limit counter straight out of SQLite.
 *
 * Deliberately not going through Drizzle: the point of these assertions is what
 * actually landed on disk, and the key format is an implementation detail of
 * `consumeRateLimit` that a test should not have to reimplement to check it.
 */
function readCounter(
  native: Database.Database,
  action: string,
  identity: string,
): { count: number; window_start: number } {
  const row = native
    .prepare("SELECT count, window_start FROM rate_limit_counters WHERE key = ?")
    .get(`${action}:${identity}`) as { count: number; window_start: number } | undefined;
  if (!row) {
    throw new Error(`No rate limit counter stored for ${action}:${identity}`);
  }
  return row;
}

function eqId(id: string) {
  return eq(schema.menuItems.id, id);
}

describe("audit repository", () => {
  it("records one row per action with JSON metadata", async () => {
    const { db, native } = createDatabase();
    try {
      const { itemId } = seedFixture(db);

      await recordAuditLog(db, {
        actorId: "user-1",
        action: "menu_item.price_updated",
        entityType: "menu_item",
        entityId: itemId,
        metadata: { from: 900, to: 950 },
      });
      await recordAuditLog(db, {
        actorId: "user-1",
        action: "menu_item.image_replaced",
        entityType: "menu_item",
        entityId: itemId,
        metadata: { from: null, to: "menu/2026/x.png" },
      });

      const all = await listAuditLogs(db);
      expect(all).toHaveLength(2);
      expect(all.map((log) => log.action).sort()).toEqual([
        "menu_item.image_replaced",
        "menu_item.price_updated",
      ]);

      const parsed = JSON.parse(all[0]?.metadata ?? "{}") as Record<string, unknown>;
      expect(Object.keys(parsed).length).toBeGreaterThan(0);

      const forItem = await findAuditLogs(db, "menu_item", itemId);
      expect(forItem).toHaveLength(2);
    } finally {
      native.close();
    }
  });

  it("stores a null actor for a pre-auth attempt", async () => {
    const { db, native } = createDatabase();
    try {
      await recordAuditLog(db, {
        actorId: null,
        action: "auth.login_failed",
        entityType: "session",
        entityId: "unknown",
      });

      const [log] = await listAuditLogs(db);
      expect(log?.actorId).toBeNull();
    } finally {
      native.close();
    }
  });
});

describe("owner authorization query", () => {
  it("returns the profile for an owner", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      const profile = await findOwnerProfile(db, "user-1");
      expect(profile?.role).toBe("owner");
    } finally {
      native.close();
    }
  });

  it("returns null for an unknown user", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      expect(await findOwnerProfile(db, "nobody")).toBeNull();
    } finally {
      native.close();
    }
  });

  it("returns null when the profile row is missing even if the user exists", async () => {
    const { db, native } = createDatabase();
    try {
      seedFixture(db);
      db.delete(schema.profiles).run();
      expect(await findOwnerProfile(db, "user-1")).toBeNull();
    } finally {
      native.close();
    }
  });
});

describe("rate limiter", () => {
  it("allows up to the limit then denies within the window", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 3, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      const first = await consumeRateLimit(db, "user-1", rule, now);
      const second = await consumeRateLimit(db, "user-1", rule, now);
      const third = await consumeRateLimit(db, "user-1", rule, now);
      const fourth = await consumeRateLimit(db, "user-1", rule, now);

      expect(first.allowed).toBe(true);
      expect(second.allowed).toBe(true);
      expect(third.allowed).toBe(true);
      expect(fourth.allowed).toBe(false);
      expect(third.remaining).toBe(0);
      expect(fourth.retryAfterSeconds).toBeGreaterThan(0);
    } finally {
      native.close();
    }
  });

  it("resets on the next window", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 1, windowSeconds: 60 };
      const start = new Date("2026-01-15T10:00:00Z");

      expect((await consumeRateLimit(db, "user-1", rule, start)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", rule, start)).allowed).toBe(false);

      const nextWindow = new Date("2026-01-15T10:01:00Z");
      expect((await consumeRateLimit(db, "user-1", rule, nextWindow)).allowed).toBe(true);
    } finally {
      native.close();
    }
  });

  it("keys on identity and action independently", async () => {
    const { db, native } = createDatabase();
    try {
      const priceRule = { action: "menu_item.update_price", limit: 1, windowSeconds: 60 };
      const imageRule = { action: "menu_item.replace_image", limit: 1, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      expect((await consumeRateLimit(db, "user-1", priceRule, now)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", priceRule, now)).allowed).toBe(false);

      // A different action, and a different identity, are both unaffected.
      expect((await consumeRateLimit(db, "user-1", imageRule, now)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-2", priceRule, now)).allowed).toBe(true);
    } finally {
      native.close();
    }
  });

  it("counts the first call in the window rather than starting at zero", async () => {
    // A first call that stored count = 0 would let a caller spend `limit + 1`
    // attempts, because the limit is compared against the value after the write.
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 1, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      const first = await consumeRateLimit(db, "user-1", rule, now);
      expect(first.allowed).toBe(true);
      expect(readCounter(native, rule.action, "user-1").count).toBe(1);
    } finally {
      native.close();
    }
  });

  it("increments the stored count in the same statement that returns it", async () => {
    // The previous implementation read the row, then wrote it back. Two callers in
    // the same window could both read `count = 1` and both write `count = 2`, so the
    // limiter under-counted. Asserting on the stored row is what catches that: a
    // lost update is invisible in the returned `remaining` alone, since both callers
    // would still see a plausible number.
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 5, windowSeconds: 60 };
      const now = new Date("2026-01-15T10:00:00Z");

      await consumeRateLimit(db, "user-1", rule, now);
      await consumeRateLimit(db, "user-1", rule, now);
      await consumeRateLimit(db, "user-1", rule, now);

      expect(readCounter(native, rule.action, "user-1").count).toBe(3);
    } finally {
      native.close();
    }
  });

  it("resets the stored window and count together in one statement", async () => {
    // The window rollover is the case a `setWhere` implementation got wrong: it
    // updated the count but left `window_start` behind, so the counter either
    // expired immediately or never. Both fields must move in one write.
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 5, windowSeconds: 60 };
      const start = new Date("2026-01-15T10:00:00Z");
      const nextWindow = new Date("2026-01-15T10:01:00Z");

      await consumeRateLimit(db, "user-1", rule, start);
      await consumeRateLimit(db, "user-1", rule, start);
      const rollover = await consumeRateLimit(db, "user-1", rule, nextWindow);
      expect(rollover.allowed).toBe(true);

      const stored = readCounter(native, rule.action, "user-1");
      expect(stored.count).toBe(1);
      expect(stored.window_start).toBe(Math.floor(nextWindow.getTime() / 1000));
      // `remaining` is derived from the stored count, so this is the same fact
      // reaching the caller rather than a second independent source.
      expect(rollover.remaining).toBe(4);
    } finally {
      native.close();
    }
  });

  it("keeps counting from 1 in a later window until the limit again", async () => {
    // Closes the loop between the two halves of a rollover: the new window starts
    // fresh, but it is still enforced rather than granting an unbounded allowance.
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 2, windowSeconds: 60 };
      const start = new Date("2026-01-15T10:00:00Z");
      const nextWindow = new Date("2026-01-15T10:01:00Z");

      await consumeRateLimit(db, "user-1", rule, start);
      await consumeRateLimit(db, "user-1", rule, start);
      expect((await consumeRateLimit(db, "user-1", rule, nextWindow)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", rule, nextWindow)).allowed).toBe(true);
      expect((await consumeRateLimit(db, "user-1", rule, nextWindow)).allowed).toBe(false);
      expect(readCounter(native, rule.action, "user-1").count).toBe(3);
    } finally {
      native.close();
    }
  });

  it("prunes counters older than a day", async () => {
    const { db, native } = createDatabase();
    try {
      const rule = { action: "menu_item.update_price", limit: 5, windowSeconds: 60 };
      await consumeRateLimit(db, "user-1", rule, new Date("2026-01-10T10:00:00Z"));

      await pruneRateLimitCounters(db, new Date("2026-01-15T10:00:00Z"));
      const after = await consumeRateLimit(db, "user-1", rule, new Date("2026-01-15T10:00:00Z"));
      expect(after.allowed).toBe(true);
    } finally {
      native.close();
    }
  });
});
